package fr.atatorus.bookservice.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-02-19T12:32:21.556+01:00
 * Generated source version: 3.2.12
 *
 */
@WebService(targetNamespace = "http://services.bookservice.atatorus.fr/", name = "Calc")
@XmlSeeAlso({ObjectFactory.class})
public interface Calc {

    @WebMethod
    @RequestWrapper(localName = "mult", targetNamespace = "http://services.bookservice.atatorus.fr/", className = "fr.atatorus.bookservice.services.Mult")
    @ResponseWrapper(localName = "multResponse", targetNamespace = "http://services.bookservice.atatorus.fr/", className = "fr.atatorus.bookservice.services.MultResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double mult(
        @WebParam(name = "nb1", targetNamespace = "")
        int nb1,
        @WebParam(name = "nb2", targetNamespace = "")
        int nb2
    );

    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "http://services.bookservice.atatorus.fr/", className = "fr.atatorus.bookservice.services.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://services.bookservice.atatorus.fr/", className = "fr.atatorus.bookservice.services.AddResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double add(
        @WebParam(name = "nb1", targetNamespace = "")
        int nb1,
        @WebParam(name = "nb2", targetNamespace = "")
        int nb2
    );

    @WebMethod
    @RequestWrapper(localName = "div", targetNamespace = "http://services.bookservice.atatorus.fr/", className = "fr.atatorus.bookservice.services.Div")
    @ResponseWrapper(localName = "divResponse", targetNamespace = "http://services.bookservice.atatorus.fr/", className = "fr.atatorus.bookservice.services.DivResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double div(
        @WebParam(name = "nb1", targetNamespace = "")
        int nb1,
        @WebParam(name = "nb2", targetNamespace = "")
        int nb2
    );

    @WebMethod
    @RequestWrapper(localName = "sous", targetNamespace = "http://services.bookservice.atatorus.fr/", className = "fr.atatorus.bookservice.services.Sous")
    @ResponseWrapper(localName = "sousResponse", targetNamespace = "http://services.bookservice.atatorus.fr/", className = "fr.atatorus.bookservice.services.SousResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double sous(
        @WebParam(name = "nb1", targetNamespace = "")
        int nb1,
        @WebParam(name = "nb2", targetNamespace = "")
        int nb2
    );

    @WebMethod
    @RequestWrapper(localName = "test", targetNamespace = "http://services.bookservice.atatorus.fr/", className = "fr.atatorus.bookservice.services.Test")
    @ResponseWrapper(localName = "testResponse", targetNamespace = "http://services.bookservice.atatorus.fr/", className = "fr.atatorus.bookservice.services.TestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String test(
        @WebParam(name = "nom", targetNamespace = "")
        java.lang.String nom
    );
}
