
package projetsoapserverclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWSGwen", targetNamespace = "http://projetSoapServerClient/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWSGwen {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://projetSoapServerClient/", className = "projetsoapserverclient.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://projetSoapServerClient/", className = "projetsoapserverclient.HelloResponse")
    @Action(input = "http://projetSoapServerClient/HelloWSGwen/helloRequest", output = "http://projetSoapServerClient/HelloWSGwen/helloResponse")
    public String hello();

    /**
     * 
     * @param x
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hellov2", targetNamespace = "http://projetSoapServerClient/", className = "projetsoapserverclient.Hellov2")
    @ResponseWrapper(localName = "hellov2Response", targetNamespace = "http://projetSoapServerClient/", className = "projetsoapserverclient.Hellov2Response")
    @Action(input = "http://projetSoapServerClient/HelloWSGwen/hellov2Request", output = "http://projetSoapServerClient/HelloWSGwen/hellov2Response")
    public String hellov2(
        @WebParam(name = "x", targetNamespace = "")
        String x);

}
