
package tpsoapdaoserver;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonneWS", targetNamespace = "http://tpSoapDaoServer/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonneWS {


    /**
     * 
     * @return
     *     returns java.util.List<tpsoapdaoserver.Personne>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "find", targetNamespace = "http://tpSoapDaoServer/", className = "tpsoapdaoserver.Find")
    @ResponseWrapper(localName = "findResponse", targetNamespace = "http://tpSoapDaoServer/", className = "tpsoapdaoserver.FindResponse")
    @Action(input = "http://tpSoapDaoServer/PersonneWS/findRequest", output = "http://tpSoapDaoServer/PersonneWS/findResponse")
    public List<Personne> find();

    /**
     * 
     * @param personne
     */
    @WebMethod
    @RequestWrapper(localName = "create", targetNamespace = "http://tpSoapDaoServer/", className = "tpsoapdaoserver.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://tpSoapDaoServer/", className = "tpsoapdaoserver.CreateResponse")
    @Action(input = "http://tpSoapDaoServer/PersonneWS/createRequest", output = "http://tpSoapDaoServer/PersonneWS/createResponse")
    public void create(
        @WebParam(name = "personne", targetNamespace = "")
        Personne personne);

    /**
     * 
     * @param id
     * @return
     *     returns tpsoapdaoserver.Personne
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findById", targetNamespace = "http://tpSoapDaoServer/", className = "tpsoapdaoserver.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://tpSoapDaoServer/", className = "tpsoapdaoserver.FindByIdResponse")
    @Action(input = "http://tpSoapDaoServer/PersonneWS/findByIdRequest", output = "http://tpSoapDaoServer/PersonneWS/findByIdResponse")
    public Personne findById(
        @WebParam(name = "id", targetNamespace = "")
        int id);

}
