
package tpsoapdaoserver;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PersonneServiceService", targetNamespace = "http://tpSoapDaoServer/", wsdlLocation = "http://127.0.0.1:8586/Personne?WSDL")
public class PersonneServiceService
    extends Service
{

    private final static URL PERSONNESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException PERSONNESERVICESERVICE_EXCEPTION;
    private final static QName PERSONNESERVICESERVICE_QNAME = new QName("http://tpSoapDaoServer/", "PersonneServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8586/Personne?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERSONNESERVICESERVICE_WSDL_LOCATION = url;
        PERSONNESERVICESERVICE_EXCEPTION = e;
    }

    public PersonneServiceService() {
        super(__getWsdlLocation(), PERSONNESERVICESERVICE_QNAME);
    }

    public PersonneServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERSONNESERVICESERVICE_QNAME, features);
    }

    public PersonneServiceService(URL wsdlLocation) {
        super(wsdlLocation, PERSONNESERVICESERVICE_QNAME);
    }

    public PersonneServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERSONNESERVICESERVICE_QNAME, features);
    }

    public PersonneServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonneServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PersonneWS
     */
    @WebEndpoint(name = "PersonneWSPort")
    public PersonneWS getPersonneWSPort() {
        return super.getPort(new QName("http://tpSoapDaoServer/", "PersonneWSPort"), PersonneWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonneWS
     */
    @WebEndpoint(name = "PersonneWSPort")
    public PersonneWS getPersonneWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tpSoapDaoServer/", "PersonneWSPort"), PersonneWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERSONNESERVICESERVICE_EXCEPTION!= null) {
            throw PERSONNESERVICESERVICE_EXCEPTION;
        }
        return PERSONNESERVICESERVICE_WSDL_LOCATION;
    }

}
